// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: his_encrypt_health_data.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct HisHealthEncrypt {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var health: HisDataHealth {
    get {return _health ?? HisDataHealth()}
    set {_health = newValue}
  }
  /// Returns true if `health` has been explicitly set.
  var hasHealth: Bool {return self._health != nil}
  /// Clears the value of `health`. Subsequent reads from it will return its default value.
  mutating func clearHealth() {self._health = nil}

  ///random number 
  var random: Data {
    get {return _random ?? Data()}
    set {_random = newValue}
  }
  /// Returns true if `random` has been explicitly set.
  var hasRandom: Bool {return self._random != nil}
  /// Clears the value of `random`. Subsequent reads from it will return its default value.
  mutating func clearRandom() {self._random = nil}

  var bleMac: Data {
    get {return _bleMac ?? Data()}
    set {_bleMac = newValue}
  }
  /// Returns true if `bleMac` has been explicitly set.
  var hasBleMac: Bool {return self._bleMac != nil}
  /// Clears the value of `bleMac`. Subsequent reads from it will return its default value.
  mutating func clearBleMac() {self._bleMac = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _health: HisDataHealth? = nil
  fileprivate var _random: Data? = nil
  fileprivate var _bleMac: Data? = nil
}

struct HisDataHealthEncrypt {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var hisHealth: HisHealthEncrypt {
    get {return _hisHealth ?? HisHealthEncrypt()}
    set {_hisHealth = newValue}
  }
  /// Returns true if `hisHealth` has been explicitly set.
  var hasHisHealth: Bool {return self._hisHealth != nil}
  /// Clears the value of `hisHealth`. Subsequent reads from it will return its default value.
  mutating func clearHisHealth() {self._hisHealth = nil}

  var signatureData: Data {
    get {return _signatureData ?? Data()}
    set {_signatureData = newValue}
  }
  /// Returns true if `signatureData` has been explicitly set.
  var hasSignatureData: Bool {return self._signatureData != nil}
  /// Clears the value of `signatureData`. Subsequent reads from it will return its default value.
  mutating func clearSignatureData() {self._signatureData = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _hisHealth: HisHealthEncrypt? = nil
  fileprivate var _signatureData: Data? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension HisHealthEncrypt: @unchecked Sendable {}
extension HisDataHealthEncrypt: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension HisHealthEncrypt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "HisHealthEncrypt"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "health"),
    2: .same(proto: "Random"),
    3: .same(proto: "BleMac"),
  ]

  public var isInitialized: Bool {
    if self._health == nil {return false}
    if self._random == nil {return false}
    if self._bleMac == nil {return false}
    if let v = self._health, !v.isInitialized {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._health) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self._random) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._bleMac) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._health {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._random {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._bleMac {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: HisHealthEncrypt, rhs: HisHealthEncrypt) -> Bool {
    if lhs._health != rhs._health {return false}
    if lhs._random != rhs._random {return false}
    if lhs._bleMac != rhs._bleMac {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension HisDataHealthEncrypt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "HisDataHealthEncrypt"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "his_Health"),
    2: .standard(proto: "signature_data"),
  ]

  public var isInitialized: Bool {
    if self._hisHealth == nil {return false}
    if self._signatureData == nil {return false}
    if let v = self._hisHealth, !v.isInitialized {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._hisHealth) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self._signatureData) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._hisHealth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._signatureData {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: HisDataHealthEncrypt, rhs: HisDataHealthEncrypt) -> Bool {
    if lhs._hisHealth != rhs._hisHealth {return false}
    if lhs._signatureData != rhs._signatureData {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
