// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: shbus_cmd.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum SBOperation: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case read // = 0
  case write // = 1

  init() {
    self = .read
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .read
    case 1: self = .write
    default: return nil
    }
  }

  var rawValue: Int {
    switch self {
    case .read: return 0
    case .write: return 1
    }
  }

}

#if swift(>=4.2)

extension SBOperation: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

struct SBDLSleepData {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var score: UInt32 {
    get {return _score ?? 0}
    set {_score = newValue}
  }
  /// Returns true if `score` has been explicitly set.
  var hasScore: Bool {return self._score != nil}
  /// Clears the value of `score`. Subsequent reads from it will return its default value.
  mutating func clearScore() {self._score = nil}

  /// minutes
  var duration: UInt32 {
    get {return _duration ?? 0}
    set {_duration = newValue}
  }
  /// Returns true if `duration` has been explicitly set.
  var hasDuration: Bool {return self._duration != nil}
  /// Clears the value of `duration`. Subsequent reads from it will return its default value.
  mutating func clearDuration() {self._duration = nil}

  /// minutes
  var deepsleep: UInt32 {
    get {return _deepsleep ?? 0}
    set {_deepsleep = newValue}
  }
  /// Returns true if `deepsleep` has been explicitly set.
  var hasDeepsleep: Bool {return self._deepsleep != nil}
  /// Clears the value of `deepsleep`. Subsequent reads from it will return its default value.
  mutating func clearDeepsleep() {self._deepsleep = nil}

  /// minutes
  var somnolence: UInt32 {
    get {return _somnolence ?? 0}
    set {_somnolence = newValue}
  }
  /// Returns true if `somnolence` has been explicitly set.
  var hasSomnolence: Bool {return self._somnolence != nil}
  /// Clears the value of `somnolence`. Subsequent reads from it will return its default value.
  mutating func clearSomnolence() {self._somnolence = nil}

  /// minutes
  var wakefulness: UInt32 {
    get {return _wakefulness ?? 0}
    set {_wakefulness = newValue}
  }
  /// Returns true if `wakefulness` has been explicitly set.
  var hasWakefulness: Bool {return self._wakefulness != nil}
  /// Clears the value of `wakefulness`. Subsequent reads from it will return its default value.
  mutating func clearWakefulness() {self._wakefulness = nil}

  /// timestamp of sleep data
  var time: RtTime {
    get {return _time ?? RtTime()}
    set {_time = newValue}
  }
  /// Returns true if `time` has been explicitly set.
  var hasTime: Bool {return self._time != nil}
  /// Clears the value of `time`. Subsequent reads from it will return its default value.
  mutating func clearTime() {self._time = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _score: UInt32? = nil
  fileprivate var _duration: UInt32? = nil
  fileprivate var _deepsleep: UInt32? = nil
  fileprivate var _somnolence: UInt32? = nil
  fileprivate var _wakefulness: UInt32? = nil
  fileprivate var _time: RtTime? = nil
}

struct SBUPSleepData {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// timestamp of current sleep data
  var time: RtTime {
    get {return _time ?? RtTime()}
    set {_time = newValue}
  }
  /// Returns true if `time` has been explicitly set.
  var hasTime: Bool {return self._time != nil}
  /// Clears the value of `time`. Subsequent reads from it will return its default value.
  mutating func clearTime() {self._time = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _time: RtTime? = nil
}

struct SBUserInfo {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String {
    get {return _name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  mutating func clearName() {self._name = nil}

  var id: String {
    get {return _id ?? String()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  var hasID: Bool {return self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  mutating func clearID() {self._id = nil}

  var card: String {
    get {return _card ?? String()}
    set {_card = newValue}
  }
  /// Returns true if `card` has been explicitly set.
  var hasCard: Bool {return self._card != nil}
  /// Clears the value of `card`. Subsequent reads from it will return its default value.
  mutating func clearCard() {self._card = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _name: String? = nil
  fileprivate var _id: String? = nil
  fileprivate var _card: String? = nil
}

struct SBCommand {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var operation: SBOperation {
    get {return _operation ?? .read}
    set {_operation = newValue}
  }
  /// Returns true if `operation` has been explicitly set.
  var hasOperation: Bool {return self._operation != nil}
  /// Clears the value of `operation`. Subsequent reads from it will return its default value.
  mutating func clearOperation() {self._operation = nil}

  /// only valid for Write
  var sleepData: SBDLSleepData {
    get {return _sleepData ?? SBDLSleepData()}
    set {_sleepData = newValue}
  }
  /// Returns true if `sleepData` has been explicitly set.
  var hasSleepData: Bool {return self._sleepData != nil}
  /// Clears the value of `sleepData`. Subsequent reads from it will return its default value.
  mutating func clearSleepData() {self._sleepData = nil}

  /// only valid for Read
  var userInfo: SBUserInfo {
    get {return _userInfo ?? SBUserInfo()}
    set {_userInfo = newValue}
  }
  /// Returns true if `userInfo` has been explicitly set.
  var hasUserInfo: Bool {return self._userInfo != nil}
  /// Clears the value of `userInfo`. Subsequent reads from it will return its default value.
  mutating func clearUserInfo() {self._userInfo = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _operation: SBOperation? = nil
  fileprivate var _sleepData: SBDLSleepData? = nil
  fileprivate var _userInfo: SBUserInfo? = nil
}

struct SBResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var operation: SBOperation {
    get {return _operation ?? .read}
    set {_operation = newValue}
  }
  /// Returns true if `operation` has been explicitly set.
  var hasOperation: Bool {return self._operation != nil}
  /// Clears the value of `operation`. Subsequent reads from it will return its default value.
  mutating func clearOperation() {self._operation = nil}

  /// only valid for Read
  var sleepData: SBUPSleepData {
    get {return _sleepData ?? SBUPSleepData()}
    set {_sleepData = newValue}
  }
  /// Returns true if `sleepData` has been explicitly set.
  var hasSleepData: Bool {return self._sleepData != nil}
  /// Clears the value of `sleepData`. Subsequent reads from it will return its default value.
  mutating func clearSleepData() {self._sleepData = nil}

  /// only valid for Read
  var userInfo: SBUserInfo {
    get {return _userInfo ?? SBUserInfo()}
    set {_userInfo = newValue}
  }
  /// Returns true if `userInfo` has been explicitly set.
  var hasUserInfo: Bool {return self._userInfo != nil}
  /// Clears the value of `userInfo`. Subsequent reads from it will return its default value.
  mutating func clearUserInfo() {self._userInfo = nil}

  var sleepDataInfo: SBDLSleepData {
    get {return _sleepDataInfo ?? SBDLSleepData()}
    set {_sleepDataInfo = newValue}
  }
  /// Returns true if `sleepDataInfo` has been explicitly set.
  var hasSleepDataInfo: Bool {return self._sleepDataInfo != nil}
  /// Clears the value of `sleepDataInfo`. Subsequent reads from it will return its default value.
  mutating func clearSleepDataInfo() {self._sleepDataInfo = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _operation: SBOperation? = nil
  fileprivate var _sleepData: SBUPSleepData? = nil
  fileprivate var _userInfo: SBUserInfo? = nil
  fileprivate var _sleepDataInfo: SBDLSleepData? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension SBOperation: @unchecked Sendable {}
extension SBDLSleepData: @unchecked Sendable {}
extension SBUPSleepData: @unchecked Sendable {}
extension SBUserInfo: @unchecked Sendable {}
extension SBCommand: @unchecked Sendable {}
extension SBResponse: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension SBOperation: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "Read"),
    1: .same(proto: "Write"),
  ]
}

extension SBDLSleepData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SBDLSleepData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "score"),
    2: .same(proto: "duration"),
    3: .same(proto: "deepsleep"),
    4: .same(proto: "somnolence"),
    5: .same(proto: "wakefulness"),
    6: .same(proto: "time"),
  ]

  public var isInitialized: Bool {
    if self._score == nil {return false}
    if self._duration == nil {return false}
    if self._deepsleep == nil {return false}
    if self._somnolence == nil {return false}
    if self._wakefulness == nil {return false}
    if self._time == nil {return false}
    if let v = self._time, !v.isInitialized {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed32Field(value: &self._score) }()
      case 2: try { try decoder.decodeSingularFixed32Field(value: &self._duration) }()
      case 3: try { try decoder.decodeSingularFixed32Field(value: &self._deepsleep) }()
      case 4: try { try decoder.decodeSingularFixed32Field(value: &self._somnolence) }()
      case 5: try { try decoder.decodeSingularFixed32Field(value: &self._wakefulness) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._time) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._score {
      try visitor.visitSingularFixed32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._duration {
      try visitor.visitSingularFixed32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._deepsleep {
      try visitor.visitSingularFixed32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._somnolence {
      try visitor.visitSingularFixed32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._wakefulness {
      try visitor.visitSingularFixed32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._time {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SBDLSleepData, rhs: SBDLSleepData) -> Bool {
    if lhs._score != rhs._score {return false}
    if lhs._duration != rhs._duration {return false}
    if lhs._deepsleep != rhs._deepsleep {return false}
    if lhs._somnolence != rhs._somnolence {return false}
    if lhs._wakefulness != rhs._wakefulness {return false}
    if lhs._time != rhs._time {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SBUPSleepData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SBUPSleepData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "time"),
  ]

  public var isInitialized: Bool {
    if self._time == nil {return false}
    if let v = self._time, !v.isInitialized {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._time) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._time {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SBUPSleepData, rhs: SBUPSleepData) -> Bool {
    if lhs._time != rhs._time {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SBUserInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SBUserInfo"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .same(proto: "id"),
    3: .same(proto: "card"),
  ]

  public var isInitialized: Bool {
    if self._name == nil {return false}
    if self._id == nil {return false}
    if self._card == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._id) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._card) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._id {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._card {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SBUserInfo, rhs: SBUserInfo) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._id != rhs._id {return false}
    if lhs._card != rhs._card {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SBCommand: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SBCommand"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "operation"),
    2: .standard(proto: "sleep_data"),
    3: .standard(proto: "user_info"),
  ]

  public var isInitialized: Bool {
    if self._operation == nil {return false}
    if let v = self._sleepData, !v.isInitialized {return false}
    if let v = self._userInfo, !v.isInitialized {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._operation) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._sleepData) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._userInfo) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._operation {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._sleepData {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._userInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SBCommand, rhs: SBCommand) -> Bool {
    if lhs._operation != rhs._operation {return false}
    if lhs._sleepData != rhs._sleepData {return false}
    if lhs._userInfo != rhs._userInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SBResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SBResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "operation"),
    2: .standard(proto: "sleep_data"),
    3: .standard(proto: "user_info"),
    4: .standard(proto: "sleep_data_info"),
  ]

  public var isInitialized: Bool {
    if self._operation == nil {return false}
    if let v = self._sleepData, !v.isInitialized {return false}
    if let v = self._userInfo, !v.isInitialized {return false}
    if let v = self._sleepDataInfo, !v.isInitialized {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._operation) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._sleepData) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._userInfo) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._sleepDataInfo) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._operation {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._sleepData {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._userInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._sleepDataInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SBResponse, rhs: SBResponse) -> Bool {
    if lhs._operation != rhs._operation {return false}
    if lhs._sleepData != rhs._sleepData {return false}
    if lhs._userInfo != rhs._userInfo {return false}
    if lhs._sleepDataInfo != rhs._sleepDataInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
