// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: his_gnss_data.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct HisDataGNSS {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var timeStamp: DateTime {
    get {return _timeStamp ?? DateTime()}
    set {_timeStamp = newValue}
  }
  /// Returns true if `timeStamp` has been explicitly set.
  var hasTimeStamp: Bool {return self._timeStamp != nil}
  /// Clears the value of `timeStamp`. Subsequent reads from it will return its default value.
  mutating func clearTimeStamp() {self._timeStamp = nil}

  var frequency: UInt32 {
    get {return _frequency ?? 0}
    set {_frequency = newValue}
  }
  /// Returns true if `frequency` has been explicitly set.
  var hasFrequency: Bool {return self._frequency != nil}
  /// Clears the value of `frequency`. Subsequent reads from it will return its default value.
  mutating func clearFrequency() {self._frequency = nil}

  var gnss: [RtGNSS] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _timeStamp: DateTime? = nil
  fileprivate var _frequency: UInt32? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension HisDataGNSS: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension HisDataGNSS: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "HisDataGNSS"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "time_stamp"),
    2: .same(proto: "frequency"),
    3: .same(proto: "gnss"),
  ]

  public var isInitialized: Bool {
    if self._timeStamp == nil {return false}
    if self._frequency == nil {return false}
    if let v = self._timeStamp, !v.isInitialized {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.gnss) {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._timeStamp) }()
      case 2: try { try decoder.decodeSingularFixed32Field(value: &self._frequency) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.gnss) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._timeStamp {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._frequency {
      try visitor.visitSingularFixed32Field(value: v, fieldNumber: 2)
    } }()
    if !self.gnss.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.gnss, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: HisDataGNSS, rhs: HisDataGNSS) -> Bool {
    if lhs._timeStamp != rhs._timeStamp {return false}
    if lhs._frequency != rhs._frequency {return false}
    if lhs.gnss != rhs.gnss {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
